Update dendron.topic.publishing.quickstart.publishing-your-site.md
dendronhq/dendron-site pull request #136
Opened 2021-07-05 22:58 UTC by andrey-jef

Add the instruction to use command `Dendron: Worksapce: Sync` next to `git add commit push`  chain in the last step. I'm not sure whether it simplify or give too much information for new user. But actually, as a non-tech user, I prefer to learn the existence of the command `Dendron: Worksapce: Sync` which is much simpler and intuitive to use

2021-07-07 22:51 UTC, kevinslin requested changes
heads up, if you use the wiki link `[[Workspace: Sync|dendron.topic.commands#workspace-sync]]`, dendron will automatically convert this into the url :)

2021-07-07 23:20 UTC, andrey-jef commented
kk, thanks. TIL this :)
Since I edit / make PR via the github web gui, so I don't see the suggestion to autocomplete such wiki link :D

2021-07-08 00:44 UTC, kevinslin approved these changes

2021-07-08 00:45 UTC, merged

2021-07-08 00:45 UTC, kevinslin commented
all good. i made the change inline. thanks for adding in the details :)