Docs: Fix inconsistent capitalization
dendronhq/dendron-site pull request #334
Opened 2021-12-23 16:07 UTC by cconrad

Fixes #333

2021-12-23 23:04 UTC, ScriptAutomate requested changes
Initial review. Most of this looks great! I'm mostly concerned with changes to headers in files, so I've marked where I noticed a `Dendron: Rename Header` command may need to be done, since you'd want to have the header be the original name, then use Dendron to rename to the ideal title (updates all wikilinks and note refs, if there are any, pointing to it).

2021-12-23 23:04 UTC, ScriptAutomate commented on vault/dendron.topic.publish.faq.md
> +This is because Next.JS will do just in time compilation of pages as they are being fetched in this mode.
```suggestion
This is because Next.js will do just in time compilation of pages as they are being fetched in this mode. 
```

2021-12-23 23:05 UTC, ScriptAutomate commented
For tracking purposes, just want to confirm and log these for future reference when looking at something like [Vale](https://docs.errata.ai/) and/or other tooling.

## Your Updates

```
next.js|NextJS|Next.js
markdown|Markdown
markdown based|Markdown-based
github|GitHub
github actions|GitHub Actions
linkedin|LinkedIn
vscode|VS Code
twitter|Twitter
dendron|Dendron
obsidian|Obsidian
json|JSON
jekyll|Jekyll
dendron cli|Dendron CLI
vim|Vim
pdf|PDF
css|CSS
obsidian|Obsidian
youtube|YouTube
svg|SVG
js|JS
scss|SCSS
dendron//|dendron://
cli|CLI
edge browser|Edge browser
react|React (in reference to the technology, harder to catch properly)
emacs|Emacs
etc|etc.
sublime text|Sublime Text
microsoft word|Microsoft Word
now a days|nowadays
vs code insider|VS Code Insider
elasticsearch|Elasticsearch
vscodium|VSCodium
evernote|Evernote
github flavored markdown|GitHub Flavored Markdown
facebook|Facebook
github pages|GitHub Pages
wikipedia|Wikipedia
```

### Dendron Features

```
dendron next|Dendron Next
seed membership|Seed membership
```

### Dendron Extensions

```
dendron markdown preview|Dendron Markdown Preview
```

## Potential others to add

Makes me think other updates can end up being made:

```
discord|Discord
rfc|RFC
gitlab|GitLab
foam|Foam
chrome|Chrome
firefox|Firefox
```

2021-12-25 12:25 UTC, cconrad commented on vault/changelog.release.2020-08-02.md
> +Dendron lets you publish the contents of your vault, either in its entirety or only a subset. Notes are published under the [Dendron-Jekyll theme](https://github.com/dendronhq/dendron-jekyll).
Agree, and removed the dash from the title case name.

2021-12-25 12:26 UTC, cconrad commented on vault/dendron.guides.troubleshooting.md
> +  - you have the Vim extension installed and it is overriding the default Dendron shortcut
I'm fine with both spellings and have adopted your suggestion - this should probably be part of the style guide.

2021-12-25 12:27 UTC, cconrad commented on vault/dendron.topic.publish.faq.md
> +This is because Next.JS will do just in time compilation of pages as they are being fetched in this mode.
Thanks 😊

2021-12-25 12:28 UTC, cconrad commented
Thanks for the info about "Rename header". I jumped into Dendron without much instruction and only recently started using wikilinks to headers, believing I would have to fix references manually when changing them. This is good to know and I've now used that feature to re-rename the headers. Also agree with all your suggestions, and fixed the potential others (Discord, RFC, GitLab, Foam, Chrome; Firefox was not mentioned anywhere) and a few more (Google, Gmail, Airtable, Roam).

2021-12-28 17:38 UTC, ScriptAutomate requested changes
Saw there were some unresolved items still: wanting to verify they were addressed, as those are my remaining items of interest. Everything else looks good.

2021-12-28 17:38 UTC, ScriptAutomate commented on vault/dendron.faq.md
> +### VS Code Snippets are not working in Frontmatter
@cconrad Want to confirm: Was this addressed?

2021-12-28 17:38 UTC, ScriptAutomate commented on vault/dendron.guides.tips.md
> +## Other VS Code Extensions
@cconrad Want to confirm: Was this addressed?

2021-12-28 17:38 UTC, ScriptAutomate commented on vault/dendron.guides.workflows.bullet-journal.md
> +## VS Code Commands
@cconrad Want to confirm: Was this addressed?

2021-12-28 17:38 UTC, ScriptAutomate commented on vault/dendron.roadmap.project.cook.md
> +## Access Dendron Repo issues inside VS Code (optional)
@cconrad Want to confirm: Was this addressed?

2021-12-28 19:13 UTC, cconrad commented
Yes, all those were addressed in commit 378cb49204cc1d59cb76a3bd0b4d6c4ff5f7e3c7, some of my clicks did'nt register here :)

2021-12-28 19:26 UTC, cconrad reviewed
Yes, all those were addressed in commit 378cb49, some of my clicks didn't register here :)

2021-12-29 02:28 UTC, ScriptAutomate approved these changes
I fixed all merge conflicts, as we had a release today that involved updates to our docs.

I will merge tomorrow.

For my own reference, I had to do the following:
```bash
# Checkout your PR using GitHub CLI
# https://github.com/cli/cli
gh pr checkout 334

# Merge latest from master
git merge master

##
# Fix merge conflicts
##

# Push to your branch
git push git@github.com:cconrad/dendron-site.git HEAD:master
```

2021-12-29 02:38 UTC, merged

2021-12-29 02:42 UTC, ScriptAutomate commented
Thanks for your contributions!! :partying_face: :seedling: :memo:

2021-12-29 03:19 UTC, ScriptAutomate commented
Related: https://github.com/dendronhq/dendron-site/issues/339